# Generated by Django 3.1.7 on 2021-03-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='correo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='nombre',
            field=models.TextField(default=''),
        ),
    ]
