# Generated by Django 3.1.7 on 2021-03-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210312_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nombre',
            new_name='text',
        ),
    ]
