# Generated by Django 3.1.7 on 2021-03-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210312_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='nombre',
        ),
    ]
